services:
  - type: web
    name: weather-prediction-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: weather-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1